### ISSUE TITLE
how to enable this shader

### ISSUE THREAD

**Issue by snowflakye** [DragonWrangler1/minetest-5.8.0-shaderpack#1]
i would like to know how to import and enable this shader in minetest, could you add the instructions in the readme file

 i tried copying the repo putting the directory in ~/.var/app/net.minetest.Minetest/.minetest/ i use the flatpak version, and in advanced settings: shader path: to the directory i put in earlier, didn't work

best regards snowflake.

**Comment by DragonWrangler1** [comment]
Everything seems correct, though did you close your minetest application and reopen it ? That's always required to change the shaders.

**Comment by DragonWrangler1** [comment]
An example (at least for my linux device) I put the folder in /home then I set it in the advanced settings to /home/user/packname (just an example) then restart the whole application and it's enabled.

**Comment by snowflakye** [comment]
[fixed] now it works !!, im sorry for wasting your time, idk what i did to get it working, you can close this issue now, but can you please still include simple instructions how to enable it on the README file,

idk what the issue was, sorry again

**Comment by DragonWrangler1** [comment]
snowflakye: No worries. I'll add it to the readme shortly :)
