### ISSUE TITLE
Shader only turns entities black

### ISSUE THREAD

**Issue by mark-wiemer** [DragonWrangler1/minetest-5.8.0-shaderpack#2]
I've cloned the repo and set `shader_path` to the location of the repo. However, the only change in Luanti 5.10.0 is that entities and held items are pitch black :(

![image](https://github.com/user-attachments/assets/4e6a5847-57e5-4145-ae2e-f1c29995441c)

In Luanti 5.8.0, there is no change at all.

Any ideas what might be going wrong? I'm on Windows using the win64 build

**Comment by DragonWrangler1** [comment]
This is not compatible for 5.10.0 it was made specifically for 5.8.0

Are dynamic shadows enabled ?

**Comment by mark-wiemer** [comment]
Ah, I didn't enable dynamic shadows.

You're welcome to close this one, I'll be using 5.10.0's new visual effects :) https://github.com/minetest/minetest/pull/14610
